apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-api
  template:
    metadata:
      labels:
        app: server-api
    spec:
      containers:
        - name: server-api
          image: ranger03/server-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "pass"
            - name: POSTGRES_DB
              value: "LeaderBoard"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
