apiVersion: v1
kind: Service
metadata:
  name: server-api-service
spec:
  selector:
    app: server-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Example NodePort for external access
  type: NodePort
